### ISSUE TITLE
could not open bpf map: addr_proxy2gameserver_port, error: Operation not permitted

### ISSUE THREAD

**Issue by that-is-not-great** [spumer/source-query-proxy-kernel-module#8]
`sqproxy run`
`could not open bpf map: addr_proxy2gameserver_port, error: Operation not permitted`

why can I not run without sudo?

```
$ ls -l /usr/src/sqredirect
total 24
-rw-r--r-- 1 root root    22 Sep  6 00:31 __init__.py
-rw-r--r-- 1 root root  3450 Sep  6 00:31 redirect.c
-rw-r--r-- 1 root root 10038 Sep  6 00:31 redirect.py
-rw-r--r-- 1 root root  1349 Sep  6 00:31 utils.h
$ ll /usr/local/bin/sqredirect
-rwxr-xr-x 1 root root 86 Sep  6 00:32 /usr/local/bin/sqredirect*
$ cat /usr/local/bin/sqredirect
#!/bin/bash

cd /usr/src/sqredirect
exec python3 /usr/src/sqredirect/redirect.py "$@"
$ python --version
Python 3.10.3
$ python3 --version
Python 3.10.3
$ groups
user sudo network
$ sudo cat /etc/sudoers.d/network
%network ALL=(root) NOPASSWD: /usr/local/bin/sqredirect
$ sudo visudo  
# ...
#includedir /etc/sudoers.d
```

```
$ /usr/local/bin/sqredirect -p 27015:30015
2024-09-06 15:11:04,956 [INFO] [main] Interface not provided
2024-09-06 15:11:04,956 [WARNING] [pyroute2.ipdb.main] Deprecation warning https://docs.pyroute2.org/ipdb_toc.html
2024-09-06 15:11:04,956 [WARNING] [pyroute2.ipdb.main] To remove this DeprecationWarning exception, start IPDB(deprecation_warning=False, ...)
2024-09-06 15:11:04,971 [INFO] [main] Use interface for default route: enp4s0
2024-09-06 15:11:04,971 [WARNING] [pyroute2.ipdb.main] Deprecation warning https://docs.pyroute2.org/ipdb_toc.html
2024-09-06 15:11:04,971 [WARNING] [pyroute2.ipdb.main] To remove this DeprecationWarning exception, start IPDB(deprecation_warning=False, ...)
2024-09-06 15:11:04,976 [INFO] [main] Building eBPF program ..., cflags=['-include', 'utils.h']
could not open bpf map: addr_proxy2gameserver_port, error: Operation not permitted
Traceback (most recent call last):
  File "/usr/src/sqredirect/redirect.py", line 348, in <module>
    sqredirect()
  File "/usr/src/sqredirect/redirect.py", line 342, in sqredirect
    main(args.ports, args.interface)
  File "/usr/src/sqredirect/redirect.py", line 152, in main
    bpf = BPF(src_file="redirect.c", cflags=cflags, debug=0)
  File "/home/user/.pyenv/versions/3.10.3/lib/python3.10/site-packages/bcc-0.31.0+6acb86ef-py3.10.egg/bcc/__init__.py", line 505, in __init__
Exception: Failed to compile BPF module b'redirect.c'
```

**Comment by that-is-not-great** [comment]
yaml config fixed
